2019-07-15 15:39:50,734 ERROR: Exception on /user/test_user [GET] [in /Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py:1780]
Traceback (most recent call last):
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 2311, in wsgi_app
    response = self.full_dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1834, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1737, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/_compat.py", line 36, in reraise
    raise value
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1832, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/app.py", line 1818, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/Users/EZ/Documents/git_projects/microblog/app/routes.py", line 83, in user_profile
    return render_template('user_profile.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 135, in render_template
    context, ctx.app)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask/templating.py", line 117, in _render
    rv = template.render(context)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/Users/EZ/Documents/git_projects/microblog/app/templates/user_profile.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/Users/EZ/Documents/git_projects/microblog/app/templates/base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 1, in top-level template code
    {% block doc -%}
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 4, in block "doc"
    {%- block html %}
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 20, in block "html"
    {% block body -%}
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/flask_bootstrap/templates/bootstrap/base.html", line 23, in block "body"
    {% block content -%}
  File "/Users/EZ/Documents/git_projects/microblog/app/templates/base.html", line 51, in block "content"
    {% block app_content %}{% endblock %}
  File "/Users/EZ/Documents/git_projects/microblog/app/templates/user_profile.html", line 14, in block "app_content"
    <p>{{ _('%(count)s followers', followers=user.followers.count()) }}, {{ _('%(count)s following', count=user.followed.count()) }}</p>
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/jinja2/ext.py", line 143, in gettext
    return rv % variables
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/Users/EZ/Documents/git_projects/microblog/venv/lib/python3.7/site-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'count'
